
name: Azure App Service - jacob-team-check, Build and deploy DotnetCore app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-and-deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test with dotnet
      run: dotnet test --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      #substitute production appsettings entries to appsettings json file
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.DOTNET_ROOT}}/myapp/appsettings.json'
      env:
        ConnectionStrings.server: ${{ secrets.AZURE_COSMOS_DB_CONNECTIONSTRING_95263D9A58B64AFFBB2E6128F18027C6 }}

      #substitute production appsettings entries to appsettings json file
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.DOTNET_ROOT}}/myapp/appsettings.json'
      env:
        ConnectionStrings.AppConfig: ${{ secrets.AZURE_CONFIG_CONNECTIONSTRING_BEC2FCC2DC4B4AF89409773F65C5C009 }}


    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: jacob-team-check
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EA1CEE0A7CBE49D1A7DFB30D6AC11FDB }}
        package: ${{env.DOTNET_ROOT}}/myapp
